### ISSUE TITLE
Usage of the `extensions` property

### ISSUE THREAD

**Issue by siniradam** [br14n-sol/inquirer-file-selector#1]
I've tried both ```extensions:["env"]``` and ```extensions:[".env"]``` but it didn't work, maybe because the file itself is just an extension.

Would you consider also accepting a function for this property? 
So we could use stuff like regex.

Eg. 
```js
      const filePath = await fileSelector({
      message: "Select an env file to work with",
      extensions: filename => filename.match(/\.env(\.\w+)?/),
    });
```

**Comment by br14n-sol** [comment]
> I've tried both `extensions:["env"]` and `extensions:[".env"]` but it didn't work, maybe because the file itself is just an extension.

What version of the package are you using?
At least in the most recent version, it works correctly for me 🤔

```js
await fileSelector({
  message: 'Select a file:',
  extensions: ['.env']
})
```

![Animation](https://github.com/user-attachments/assets/d71ef095-d6e2-4778-a26c-9e4a917a99e8)

**Comment by br14n-sol** [comment]
> Would you consider also accepting a function for this property? So we could use stuff like regex.
> 
> Eg.
> 
> ```js
>       const filePath = await fileSelector({
>       message: "Select an env file to work with",
>       extensions: filename => filename.match(/\.env(\.\w+)?/),
>     });
> ```

The truth looks useful, especially if you want something more specific than a simple array with extensions.
Although I don't know if it would be clearer to move it to a separate property something like that:

```ts
filter: (file: Item) => boolean
```

**Comment by siniradam** [comment]
Although that would be ok, you'd end up with 2 different parameters that provides the same functionality, also you have to decide if one overrides the other when both parameters are present.

I've seen some examples of parameter takes both string and function, it shouldn't be something uncommon. Decide is yours. I've sent a push request as a sample if you'd like to check it out.

Cheers.

**Comment by br14n-sol** [comment]
Thinking it calmly, I believe that the simplest thing would be to add a `match` property that acts as callback:

```ts
match: (file: Item) => boolean
```

So each user can decide how to filter their files based on their actual need, in the end it would be less code to keep in the package in the long run.

The `extensions` property would be marked as deprecated to remove it completely in version 1.0.0.
