### ISSUE TITLE
Incompatibilty with older node versions due to `dirent.parentPath` usage

### ISSUE THREAD

**Issue by ilya-zakirzyanov** [br14n-sol/inquirer-file-selector#14]
Hi @br14n-sol ! Thanks for the cool inquirer extension. While adding your extension to my project, I encountered an issue 
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
```

I did some investigation, and it turned out that you use `dirent.parentPath` in your tool. However, this option is still marked as Experimental in the [official doc](https://nodejs.org/api/fs.html#direntparentpath) and was added in the quite recent node version `20.12.0`. In one of my projects, I could easily migrate to the newer node version, but for another one where I want to use your tool, it would be quite challenging. What do you think of making it more compatible with older node versions and avoiding usage of `dirent.parentPath`. I can prepare a pull request if you agree with the change.

**Comment by br14n-sol** [comment]
Hello, what version of node are you using?

According to the [documentation](https://nodejs.org/docs/latest-v18.x/api/fs.html#direntparentpath) `dirent.parentPath` was added in node 18.20.0

**Comment by br14n-sol** [comment]
I understand that if you use a version >= 18 and < 18.20.0 this would give problems.

**Comment by br14n-sol** [comment]
If you want to make a pull request, it's always welcome, otherwise I'll take a look tomorrow.

**Comment by br14n-sol** [comment]
This will be corrected in the next version.
Thank you for reporting it 👍

**Comment by ilya-zakirzyanov** [comment]
Thanks! Yes, in one of the projects, we still use node 18.16.1, and in another one 20.10.0. Thanks for the quick reaction!
