### ISSUE TITLE
Add option to match / exclude folders

### ISSUE THREAD

**Issue by GLPG35** [br14n-sol/inquirer-file-selector#22]
The library provides options for file matching, but not folders, making it hard to, for example, exclude hidden folders. It would go well along with the folder selection PR #20

**Comment by br14n-sol** [comment]
Allowing directory filtering could break the navigation as it is currently implemented.

I will probably change this in #24, although at the moment I have no idea how to approach it.

**Comment by br14n-sol** [comment]
Hi, I forgot to link the pr #27, which solves this problem.
