### ISSUE TITLE
Feature Proposal: A `loop` boolean to allow looping in file selector

### ISSUE THREAD

**Issue by amsyarzero** [br14n-sol/inquirer-file-selector#30]
Good day! First off, thank you so much for making this amazing terminal file selector. It really works wonders 😁

I would like to propose a feature: a `loop` boolean inside the file selector object that will allow looping, similar to [`@inquirer/select`](https://github.com/SBoudrias/Inquirer.js/tree/main/packages/select). Let me know if I can help with coding it too; although unfamiliar with this; I don't mind a challenge.

Again, thank you for this terminal utility 😁

**Comment by br14n-sol** [comment]
It is something simple to implement, initially it would be included in the first version, but for purely aesthetic reasons at the time I decided not to include it. 😅

It will be included in the next version, honestly I am not sure when I will publish it, but I will try to do it in the next few days.

**Comment by amsyarzero** [comment]
I see, and no worries! It's not an urgent request, more so aesthetic like you stated.

**Comment by amsyarzero** [comment]
Loop works perfectly, thank you so much!
