### ISSUE TITLE
Feature Proposal: Hiding files that doesn't match with `extension` criteria

### ISSUE THREAD

**Issue by siniradam** [br14n-sol/inquirer-file-selector#4]
Another property can be added in order to hide files that doesn't match with 'extensions' therefore navigation through files would be faster.

```js
const filePath = await fileSelector({
  message: 'Select a file:',
  extensions:["jpg","png"],
  hideNonMatch:true
})
```

**Comment by br14n-sol** [comment]
I had already started working on it, so it should be present in the next version, maybe today or tomorrow.
